### ISSUE TITLE
User selects the snow dump button

### ISSUE THREAD

**Issue by asfopoo** [YCPRadioTelescope/rtMobile#10]
1. User opens the app
2. Server authenticates device id
3. User is taken to the Home Screen
4. User selects "snow dump " button
5. Telescope points at the lowest elevation possible, then moves back up into stow.

1a. User does not have login credentials
1. User must create credentials on the website.
1b. User has never opened the app
1. User enters login credentials
2a. User id is not authenticated
1. User must get device id into the server
4a. A broken sensor is keeping the user from moving the telescope

Notification pops up telling user which sensor is broken and that they cannot move the telescope right now

**Comment by amcdevitt97** [comment]
Copy current tcp code into snow-dump function with different coordinates, just change the host IP to whatever the middleman IP will be
